# Obtener la imagen que necesitamos
FROM node:14

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

#CMD ["node", "index.js"]
CMD ["node", "./src/index.js"]
#CMD ["npm", "start"]