apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-py2
  template:
    metadata:
      labels:
        app: kafka-py2
    spec:
      containers:
      - name: consumer
        #image: gcr.io/pure-advantage-305004/consumerkafka
        image: mickyxd/consumerkafka
        #ports:
        #- containerPort: 8000
      - name: producer
        #image: gcr.io/pure-advantage-305004/producerkafka
        image: mickyxd/producerkafka
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-py2
  ports:
    - port: 8000
      targetPort: 8000
      #nodePort: 31000
  #type: LoadBalancer
  type: NodePort